version: '3.8'

services:
  api:
    build: .
    image: ghcr.io/zprtall/eat:latest
    container_name: API
    working_dir: /app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
      - .:/app

  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_US}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=postgres_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_REGISTRY_USER=${GHCR_US}
      - WATCHTOWER_REGISTRY_PASSWORD=${GHCR_PASS}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60

volumes:
  pgdata:
