version: '3.8'

services:
  api:
    image: ghcr.io/zprtall/eat:latest
    container_name: api
    working_dir: /app
    env_file:
      - .env
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers
      "
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
      - ./alembic/versions:/app/alembic/versions


  celery_worker:
    image: ghcr.io/zprtall/eat:latest
    container_name: celery_worker
    env_file:
      - .env
    command: celery -A app.core.celery worker --loglevel=info
    depends_on:
      - redis
      - postgres
    restart: always


  celery_beat:
    image: ghcr.io/zprtall/eat:latest
    container_name: celery_beat
    env_file:
      - .env
    command: celery -A app.core.celery beat --loglevel=info
    depends_on:
      - redis
      - postgres
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Minsk
      - WATCHTOWER_REGISTRY_USER=${GHCR_US}
      - WATCHTOWER_REGISTRY_PASSWORD=${GHCR_PASS}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
      - DOCKER_API_VERSION=1.44

volumes:
  pgdata: