"""initial migration

Revision ID: 32c6a6549032
Revises: 
Create Date: 2026-07-07 13:17:53.545946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c6a6549032'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('habit_times', sa.JSON(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('body_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('neck', sa.Float(), nullable=False),
    sa.Column('shoulder', sa.Float(), nullable=False),
    sa.Column('forearm', sa.Float(), nullable=False),
    sa.Column('chest_on_exhale', sa.Float(), nullable=False),
    sa.Column('chest_on_the_inhale', sa.Float(), nullable=False),
    sa.Column('waist', sa.Float(), nullable=False),
    sa.Column('hip', sa.Float(), nullable=False),
    sa.Column('shin', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_params_id'), 'body_params', ['id'], unique=False)
    op.create_table('dishes',
    sa.Column('dishes_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_finish_dish', sa.Float(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('dishes_id')
    )
    op.create_index(op.f('ix_dishes_dishes_id'), 'dishes', ['dishes_id'], unique=False)
    op.create_table('meals',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_index(op.f('ix_meals_meal_id'), 'meals', ['meal_id'], unique=False)
    op.create_table('nutrition_daily_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_nutrition_daily_target_id'), 'nutrition_daily_target', ['id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.dishes_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.dishes_id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_nutrition_daily_target_id'), table_name='nutrition_daily_target')
    op.drop_table('nutrition_daily_target')
    op.drop_index(op.f('ix_meals_meal_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_dishes_dishes_id'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_body_params_id'), table_name='body_params')
    op.drop_table('body_params')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
